### ISSUE TITLE
Hyperapp 2

### ISSUE THREAD

**Issue by kofifus** [okwolf/hyperapp-freeze#4]
Hi does the code apply to latest hyperapp (2.x) as well ?

**Comment by okwolf** [comment]
Currently, v2 isn't supported, but if there's interest I can make an update.

**Comment by kofifus** [comment]
That would be great 👍

**Comment by okwolf** [comment]
[`0.3.0`](https://github.com/okwolf/hyperapp-freeze/releases/tag/0.3.0) is released ☺️
